version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: JUSmoo321#@!321
       MYSQL_DATABASE: dev_wordpress
       MYSQL_USER: wpmysql
       MYSQL_PASSWORD: wpmysql2021!
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8080:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wpmysql
       WORDPRESS_DB_PASSWORD: wpmysql2021!
       WORDPRESS_DB_NAME: dev_wordpress
volumes:
    db_data: {}